### ISSUE TITLE
Demos: Parties' input

### ISSUE THREAD

**Issue by jimouris** [aicis/fresco#210]
Hello,

I was looking at the demos and trying to understand them. In all demos, you have a number of parties that execute the MPC protocol, but only one of them provides the input. For example, in the aggregation demo, player 1 provides his inputs (2D matrix), as follows:
```
      // player 1 provides input
      if (root.getBasicNumericContext().getMyId() == 1) {
        closed = root.collections().closeMatrix(readInputs(), 1);
      } else {
        // if we aren't player 1 we need to provide the expected size of the input
        closed = root.collections().closeMatrix(8, 2, 1);
      }
```

Documentation does not contain any information about the input of the players. Can you explain why only one player provides input?

Thanks in advance,
Dimitris

**Comment by GuutBoy** [comment]
This is just to keep the demo simply I suspect.

There is no inherent reason why only player 1 is giving input here. It could just as well be player 2 or both players providing input to an MPC computation. 

Note that in else statement  
```Java
...
} else {
  // if we aren't player 1 we need to provide the expected size of the input
  closed = root.collections().closeMatrix(8, 2, 1);
}
...
```
The remaining players are also closing a matrix, except instead of the plaintext data they simply give the dimensions of the matrix they expect player 1 to input. This is to make sure that all parties are running the same protocols.

**Comment by Rhaea** [comment]
Assuming this question is answered. If not, you're also welcome to chat with us on Gitter or use the mailing list.
