### ISSUE TITLE
Different return values to players in AES demo

### ISSUE THREAD

**Issue by kkotowick** [aicis/fresco#336]
The AES demo is great, but is it possible to _not_ return the ciphertext to the player that sent the key?

Since the entire purpose of MPC is to prevent one party from finding out the input of the other, the way the AES demo is coded now is unrealistic. It returns the ciphertext to both players, and since one player has the key that was used to encrypt the plaintext the other player sent, he can just use that key to decrypt the ciphertext and retrieve the plaintext. It would be ideal if the ciphertext was only returned to the player who contributed the plaintext, and the player who contributed the key just got a True/False return value of whether it succeeded.

Is this possible to do securely with Fresco (i.e. a malicious player who sent the key can't edit their code to get the ciphertext as well)?

**Comment by GuutBoy** [comment]
Sure, that is possible. Just change the line `outs.add(seq.binary().open(toOpen));` to `outs.add(seq.binary().open(toOpen, 2));` in https://github.com/aicis/fresco/blob/master/demos/aes/src/main/java/dk/alexandra/fresco/demo/AesDemo.java

**Comment by kkotowick** [comment]
Thank you for the quick response. Unfortunately, this doesn't seem to be a secure solution. If we edit the code as you suggest, and both Player 1 (key) and Player 2 (plaintext) run the code:

`outs.add(seq.binary().open(toOpen, 2));`

Then this works as intended, and only Player 2 receives the ciphertext. If we assume that Player 1 is malicious, however, and changes their local code, then now the following code is being run:

Player 1:
`outs.add(seq.binary().open(toOpen));`

Player 2:
`outs.add(seq.binary().open(toOpen, 2));`

And now, even though Player 2 didn't consent to it, Player 1 still receives the ciphertext. At least, that's what's happening in the tests I'm running.

**Comment by n1v0lg** [comment]
This is happening is because you are running with the dummy suite which is inherently insecure. And you're right, TinyTables does not currently support opening to a single party (that suite was more of an experimental implementation and we're planning to drop support for it in a coming release). The reason SPDZ doesn't work here is that it's an arithmetic suite which does not support boolean protocols. SPDZ does support  MiMC (https://eprint.iacr.org/2016/492.pdf) a different symmetric enc. scheme however--I would recommend giving that a shot if you just need symmetric encryption but not necessarily AES.

**Comment by kkotowick** [comment]
Unfortunately, AES is required for my implementation. Is there no way to do this then?

**Comment by n1v0lg** [comment]
There is no out-of-the-box way to run AES in arithmetic mode unfortunately. You would have to implement it as a computation based on arithmetic operations in FRESCO (certainly doable but would require a fair amount of work). 

Regarding tiny tables: our tiny tables implementation only protects against passive adversaries (i.e., parties are required to faithfully execute the protocol). In that sense, the attack you describe is out of scope for our adversary model since an attacker is assumed to follow the protocol.

If you are okay with passive security then adding an output-to-single-party protocol should be pretty straight-forward. 

However, if you need full malicious security, tiny tables does not currently provide that even if you were to implement the single-party output protocol.

In that sense, implementing AES in arithmetic mode is probably your best bet.
