### ISSUE TITLE
How to run SPDZ applications

### ISSUE THREAD

**Issue by meilof** [aicis/fresco#34]
Hi guys,

I was playing around with FRESCO and trying to run an application using the SPDZ backend. My command lines are:

java -jar lp.jar -i1 -p1:localhost:9292 -p2:localhost:9994 -s spdz
java -jar lp.jar -i2 -p1:localhost:9292 -p2:localhost:9994 -s spdz

However, it gives the following exception:

Exception in thread "main" java.lang.NullPointerException
        at dk.alexandra.fresco.suite.spdz.storage.DataSupplierImpl.getSSK(DataSupplierImpl.java:138)
        at dk.alexandra.fresco.suite.spdz.storage.SpdzStorageImpl.getSSK(SpdzStorageImpl.java:112)
        at dk.alexandra.fresco.suite.spdz.evaluation.strategy.SpdzProtocolSuite.init(SpdzProtocolSuite.java:133)
        at dk.alexandra.fresco.framework.sce.SCEImpl.setup(SCEImpl.java:169)
        at dk.alexandra.fresco.framework.sce.SCEImpl.runApplication(SCEImpl.java:232)
        at LPTest.main(LPTest.java:67)

Debugging says that indeed, the storage is set to NULL. But how can I change this?

**Comment by meilof** [comment]
OK, I got things to work now by:

- Adding a command line option to select storage (which was not there in CmdLineUtil)
- Adding "-r STREAMED_STORAGE -D spdz.useDummyData=True" to the command line

However, it works only with dummy storage. The reason seems to be that the output of FakeTripleGen is incompatible with SpdzStorageImpl, is that correct?

**Comment by GuutBoy** [comment]
Hi Meilof. Thank you for bringing this up. We are super busy right now. But I will look into this as soon as there is some time to breathe :).

Den 13. sep. 2016 kl. 11.03 skrev meilof <notifications@github.com<mailto:notifications@github.com>>:


OK, I got things to work now by:

  *   Adding a command line option to select storage (which was not there in CmdLineUtil)
  *   Adding "-r STREAMED_STORAGE -D spdz.useDummyData=True" to the command line

However, it works only with dummy storage. The reason seems to be that the output of FakeTripleGen is incompatible with SpdzStorageImpl, is that correct?

-

**Comment by Rhaea** [comment]
Hey Meilof
I’m almost positive that the FakeTriplesGen is incompatible with the SpdzStorageImpl. We’re very sorry about this, but as Peter mentioned, have been super busy meeting deadlines. However, the difference is not extreme, and certainly not functionality wise. The biggest difference security wise is if you have a third party that generates the triples for the computing parties. In that case, the fake triple generator is useful, but otherwise it’s almost only a problem with respect to computation efficiency (dummy data uses a large prime which might not be needed, however, no disc/db access has to be done).

That is my, sort of, bad excuse for not having done something about it :)

And great with the added option. You’re most welcome to submit the change as a pull request.

--
/Kasper

**Comment by meilof** [comment]
OK, thanks for the reply, indeed I can work with the dummy data for now, and I will make a pull request if I have something useful.

By the way, another question popped up. In the SPDZ implementation, as far as I understand, MAC checking is done periodically. But then some intermediate values may be opened for which no MAC check has been performed yet. Hence an attacker can add any additive term to these opened values. This will of course be detected later, but isn't this in theory a security problem in that it allows the attacker to learn a value that it should not have access to?

**Comment by Rhaea** [comment]
Unfortunately I think you’re right. Whenever any output is done, a MAC-check should be done on the values up until that point in order to not reveal information.
We have missed this requirement in the design process it seems. We need to rethink this when we get the time.

Thanks for bringing it to our attention.

--
/Kasper

**Comment by GuutBoy** [comment]
Closing this as it should be dealt with in #152
