### ISSUE TITLE
Change SPDZ modulus

### ISSUE THREAD

**Issue by rdragos** [aicis/fresco#35]
I'm trying to run "test_LPSolver_2_Parallel_batched_dummy" inside TestSpdzLPSolver2Parties with different modulus values to see how the precision of fixed point arithmetic varies.

I've changed the "getModulus" function inside spdz/storage/DummyDataSupplierImpl.java to return a different prime but when I run the test again Fresco crashes. I guess that I should also change the data from the other functions like getSSK but I do not know what to put in there.

Can you shed some light on what those constants mean?

**Comment by Rhaea** [comment]
Hey Dragos

If you want to change the modulus, you would need to change all of the different values within the DummyDataSupplierImpl class (or at least those that you would use – likely the triples and for sure also the SSK value.

The easier way is to use instead the approach used by the “test_LPSolver_2_Sequential_streamed” test where the Boolean useDummyData is not set to true. This will cause preprocessed data to be generated on the spot. Now, you still need to change the modulus, but that is all you have to do. Do this within InitializeStorage.initStreamedStorage. Also remove the outcommented part just after the modulus where the alpha key is generated. This should be generated instead of taken from the dummy values.

However, there are certain hardcoded values used for the LP solver which, as I recall, depend on the bitlength of the modulus. Thus, any value will not work. We need to prevent overflow in the simplex algorithm which is why the modulus is this large to begin with. The input values given to the solver might need to be smaller as well if using a smaller modulus. It might also be necessary to generate more preprocessed data than the test currently does if the values are smaller.

Also, once you generate the values, they are stored persistently on disc within the directory “spdz” in the root of the project. Delete this directory if you don’t want to reuse the data.

So all in all, it is of course possible, but not necessarily easy to change the modulus.

PS. I did some small experiment on the mentioned test, using a modulus of 170141183460469231731687303715884105727 (2^127-1), but this went into an eternal loop it seemed, so here I think the overflow problem occurred such that the simplex algorithm never finishes.

That said, if you’re not doing LP solving, then it should be straightforward to change the modulus into any prime you like.
Hope all of that made sense :)

--
/Kasper

**Comment by rdragos** [comment]
Yes, now things are much clearer.
Thank you for the prompt response!
