### ISSUE TITLE
BGW suite: invalid results on even #participants

### ISSUE THREAD

**Issue by grandcat** [aicis/fresco#40]
Hi all,

I'm using Fresco as a SMC provider for my Master's Thesis and really like it!

Using the BGW protocol, an odd amount of participants `[3, 5, 7, 9, 11, ...]` produces a correct result when calculating a sum on all secret values of all participating nodes.
However, the same with an even amount of participants `[2, 4, 6, ...]` outputs an invalid result, e.g. `618970019642690137449562105`.
Prime modulus was: `618970019642690137449562111`. 
--> The difference is the correct result in that case.

Do you have any idea or is there a limitation of **BGW**?
In case you're interested, the distributed sum is the application I used:
https://github.com/grandcat/fresco/blob/protocol_evaluation/src/main/java/dk/alexandra/fresco/demo/DistSum.java#L207-L270

Thank you :)

**Comment by GuutBoy** [comment]
Thank you for reporting this. I am pretty sure this is a bug. As far as I recall BGW should work for any number of parties larger than 2. I am rather busy at the moment but I would like to look in to this as soon as I have the time.

**Comment by Rhaea** [comment]
Hello Stefan

Cool that you’re using the FRESCO framework.
Interesting question, and one that apparently escaped our test-suite since we only consider odd numbers of parties due to the constraint for handling only 1/3 corrupted parties. 
It is not a limitation of the BGW protocol suite. It is a bug somewhere in the code which we will look into.

The workaround for now, if you need to use an even number of parties, would be to convert the result manually afterwards by doing something like res = modulus - res;

**Comment by grandcat** [comment]
Thanks for the immediate replies, very appreciated.

As I have both even and odd number of participants on a dynamic basis, I apply this as a work-around for now. This is no problem.
I will test whether the difference is always the result for increasing #participants.

**Comment by GuutBoy** [comment]
Ok, I couldn't help looking into this. Turns out there was a bug in how we recombined Shamir Shares. Apparently that bug only showed it self with even numbers of players ... very strange. It should be fixed now.

**Comment by grandcat** [comment]
Thank you!
So basically, a `mod(modulus)` was missing for the addition, right?
https://github.com/aicis/fresco/commit/b699d8300a4e8f1e6d287a469dc2403b4f636dff#diff-721d269393fe7bba15d8cef290c1b03bR150

**Comment by GuutBoy** [comment]
No, it was a little more complicated than that ... Essentially we swapped two terms in a subtraction (fixed in line 163) involved in computing the coefficient used for reconstruction. Actually, I am pretty surprised it was working at all.

Btw. if you dont mind we would be very interested in knowing more about your project. And let us know if you need any help with FRESCO.

**Comment by GuutBoy** [comment]
Yikes I introduced a new bug. Should be fixed now.

**Comment by grandcat** [comment]
Thanks for the support and prompt fixes. It works now :+1: 
In a nutshell, the thesis is about orchestrating a dynamic set of distributed SMC nodes in a local network (scope: Smart Buildings, but not restricted to). Some evaluation shows that Fresco is a good fit for the SMC layer.
I can provide some information later via a private channel if desired. Code is not ready yet ;)
